export const swaggerConfig = {
  openapi: "3.0.0",
  info: {
    title: "Plum AI Adjudication API",
    version: "1.0.0",
    description: "Interactive API Documentation for the Plum AI Adjudication Engine. Provides detailed endpoints for document extraction, policy rule evaluation, and claim history."
  },
  servers: [
    {
      url: "/",
      description: "Local Development Server"
    }
  ],
  paths: {
    "/api/extract": {
      post: {
        summary: "Extract clinical data from medical documents",
        description: "Accepts base64 encoded images or PDF text and passes them to the Gemini 2.5 Flash Vision model to return a structured JSON mapping of all medical and financial entities.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  type: { type: "string", enum: ["image", "text"] },
                  base64: { type: "string" },
                  mimeType: { type: "string" },
                  text: { type: "string" }
                }
              }
            }
          }
        },
        responses: {
          "200": {
            description: "Successful document extraction.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    documentType: { type: "string", example: "PRESCRIPTION" },
                    patientName: { type: "string", example: "John Doe" },
                    treatmentDate: { type: "string", example: "2023-10-15" },
                    doctorName: { type: "string", example: "Dr. Arvind Smith" },
                    diagnosis: { type: "string", example: "Viral Fever" },
                    medicines: { type: "array", items: { type: "string" }, example: ["Paracetamol 500mg"] },
                    totalAmount: { type: "number", example: 1500 },
                    confidence: { type: "number", example: 0.98 }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/adjudicate": {
      post: {
        summary: "Run automated policy adjudication",
        description: "Executes the core rules engine against an extracted claim. Verifies 30-day filing limits, checks waiting periods, validates against the member's remaining annual balance, calculates copays/discounts, and delegates subjective medical necessity evaluations to the AI.",
        requestBody: {
          required: true,
          content: {
            "application/json": {
              schema: {
                type: "object",
                properties: {
                  memberId: { type: "string", example: "MEM001" },
                  cashlessRequest: { type: "boolean", example: false },
                  claimData: {
                    type: "object",
                    description: "The structured medical object previously generated by the /api/extract endpoint."
                  }
                }
              }
            }
          }
        },
        responses: {
          "200": {
            description: "Adjudication decision generated successfully.",
            content: {
              "application/json": {
                schema: {
                  type: "object",
                  properties: {
                    decision: { type: "string", enum: ["APPROVED", "REJECTED", "PARTIAL", "MANUAL_REVIEW"], example: "APPROVED" },
                    approvedAmount: { type: "number", example: 1350 },
                    rejectionReasons: { type: "array", items: { type: "string" } },
                    deduction: {
                      type: "object",
                      properties: {
                        copay: { type: "number", example: 150 },
                        networkDiscount: { type: "number", example: 0 }
                      }
                    },
                    aiReasoning: { type: "string", example: "Treatment aligns perfectly with the diagnosis of Viral Fever. Approved." }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/claims": {
      get: {
        summary: "Retrieve Claim History",
        description: "Fetches a chronological list of all historically processed claims alongside their AI adjudication reasoning and financial breakdowns from the PostgreSQL database.",
        responses: {
          "200": {
            description: "A comprehensive list of past claims.",
            content: {
              "application/json": {
                schema: {
                  type: "array",
                  items: {
                    type: "object",
                    properties: {
                      id: { type: "string" },
                      memberId: { type: "string", example: "MEM001" },
                      memberName: { type: "string", example: "John Doe" },
                      claimAmount: { type: "number", example: 1500 },
                      status: { type: "string", enum: ["APPROVED", "REJECTED", "PARTIAL", "PENDING"] },
                      createdAt: { type: "string", format: "date-time" }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
};
